### ISSUE TITLE
[BUG] Lock screen stuck on one image

### ISSUE THREAD

**Issue by M4MK** [t1m0thyj/WDD-scripts#1]
I changed the code as you said to change the lock screen but it's stuck on one of the images, do you know why this is so and should I provide anymore details?

When reporting a bug please provide:
 - Steps to reproduce it: No idea
 - Windows version: 10 version 1809
 - WinDynamicDesktop version: 3.0.0
 - Installation source: Microsoft Store

**Comment by t1m0thyj** [comment]
That LockScreen class is what the script is currently using. Unfortunately it doesn't work because of this: https://social.msdn.microsoft.com/Forums/vstudio/en-US/c5f7e014-a1a1-4d62-b550-7976381d62cd/change-windows-8-lockscreen-image-with-wpfservice-only-works-once?forum=wpf

**Comment by t1m0thyj** [comment]
From Gitter:
> Dev PM @pratham280 Jun 07 08:57
> In the Dynamic wallpaper for lockscreen script has an issue , when run for first time it creates a "LockScreen_A " folder (in "System Data " folder where the wallpapers are rendered) but assigns the Ownership to system which prevents the script to overwrite the files

**Comment by t1m0thyj** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #101: Lock screen stuck on one image](https://trello.com/c/8g65IlR7/18-issue-101-lock-screen-stuck-on-one-image)

**Comment by yazan1107** [comment]
you should mention that disabling Show lock screen background picture on the sign-in screen solve partly the problem!

**Comment by t1m0thyj** [comment]
Closing since WDD 5 supports changing lockscreen image directly in the app without scripts.
