### ISSUE TITLE
another instance of windynamicdesktop is running at startup

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/WDD-scripts#10]
another instance of windynamicdesktop is running at startup

- WDD Version: WinDynamicDesktop 4.7.0
- OS Version: 22000.318

Steps to Reproduce:

1. restart computer
2. i get a warning another instance of windynamicdesktop is running at startup
btw i installed the script of task scheduler(of logon)!("https://github.com/t1m0thyj/WDD-scripts/tree/master/standalone#readme")
Are you using the Microsoft Store version of WDD?: Yes/No
nos
<img width="299" alt="image" src="https://user-images.githubusercontent.com/78726445/142383492-62544a78-8bab-4bd8-9836-9b80a742123b.png">

**Comment by t1m0thyj** [comment]
Good catch, this should be fixed in 69064bc2ed42c3d633821ff3f0af3fda203d99c2
