### ISSUE TITLE
Update WDD-scripts `README.md`

### ISSUE THREAD

**Issue by Rafeqm** [t1m0thyj/WDD-scripts#17]
Delete this one:
![image](https://user-images.githubusercontent.com/87463084/163114367-cef11fec-23cb-40b5-a811-12fd0965fe92.png)

This feature is available in the main app.
![image](https://user-images.githubusercontent.com/87463084/163114113-115b6969-6e13-408a-af91-3f7559f21504.png)

Should I make a PR?

**Comment by t1m0thyj** [comment]
Thanks for noticing this and sorry for not replying sooner. The readme was updated in https://github.com/t1m0thyj/WDD-scripts/commit/98f39e0d4afa924d674bb05536cefef09145d885
