### ISSUE TITLE
no mouse cursor change on dark mode?

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/WDD-scripts#26]
no mouse cursor change on dark mode?

no mouse cursor change on dark mode?

**Comment by t1m0thyj** [comment]
@bigplayer-ai I don't have time to make a script for this right now, but contributions are welcome 🙂 See the readme for how to [create a new script](https://github.com/t1m0thyj/WDD-scripts#create-new-scripts).

**Comment by bigplayer-ai** [comment]
#31

**Comment by t1m0thyj** [comment]
Closing as duplicate of #4
