### ISSUE TITLE
Change user profile picture when "windows theme" changes(automatically).

### ISSUE THREAD

**Issue by ghost** [t1m0thyj/WDD-scripts#27]
# What is this feature? 
Change user profile picture when "windows theme" changes(automatically).
# How the feature should work?
windows changes to dark mode(there is alot of application that does this). profile picture changes from light to dark for example
# You have examples or an idea of how it can be implemented?

**Comment by t1m0thyj** [comment]
Closing since user deleted their account and no one else has upvoted this suggestion.
