### ISSUE TITLE
error when using just the auto day and night theme with a windows 7 theme pack

### ISSUE THREAD

**Issue by Goldmaster** [t1m0thyj/WDD-scripts#28]
Hi there, I have the Avatar theme installed way back from Microsoft website The exact version can be downloaded from http://avatar-windows-7-theme.en.uptodown.com.

However, I want to keep the auto day and night setting, while using the theme. But there seams to be a conflict between the theme pack and win dynamic desktop. As I will often get this error prompt.

![Screenshot 2022-12-27 220811](https://user-images.githubusercontent.com/7105970/209970273-3ad1678b-fc23-4957-a747-8690ea3ebb3d.png)

Any chance of a fix or auto update? please?

**Comment by t1m0thyj** [comment]
@Goldmaster Thanks for reporting this, could you try downloading the EXE from the latest build and let me know if it works? I believe this issue with the "imagePath" parameter has been fixed.
https://github.com/t1m0thyj/WinDynamicDesktop/actions/runs/3737520729
