### ISSUE TITLE
What is the order of running scripts?

### ISSUE THREAD

**Issue by bigplayer-ai** [t1m0thyj/WDD-scripts#35]
What is the order of running scripts?

**Comment by t1m0thyj** [comment]
They will run in the order returned by `Directory.EnumerateFiles("scripts", "*.ps1")`:
https://github.com/t1m0thyj/WinDynamicDesktop/blob/6ad489ca459bd1f33a6d9468580803def73a1960/src/ScriptManager.cs#L68

I believe that EnumerateFiles returns the list of files in alphabetical order, so `A.ps1` should consistently run before `B.ps1`.
