### ISSUE TITLE
How can I make my scripts auto update from this repo?

### ISSUE THREAD

**Issue by bigplayer-ai** [t1m0thyj/WDD-scripts#37]
Hey,
I was wondering can I make my scripts folder auto update from this repo?

**Comment by t1m0thyj** [comment]
Closing as duplicate of #19, please search to see if an issue already exists before creating a new one.

This is a WIP in the [feature-auto-update](https://github.com/t1m0thyj/WDD-scripts/tree/feature-auto-update) branch.
