### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by febrimuhnas** [t1m0thyj/WDD-scripts#48]
Hello. After updating the app to 5.5.0, I got error message like this:
![Cuplikan layar 2024-05-05 192926](https://github.com/t1m0thyj/WDD-scripts/assets/73753251/3d0e3272-1489-4e69-8150-e7c1b6632937)
![Cuplikan layar 2024-05-05 192919](https://github.com/t1m0thyj/WDD-scripts/assets/73753251/b30e521e-fbb6-4271-a0d5-57f61e714df1)

**Comment by t1m0thyj** [comment]
@febrimuhnas After updating to WinDD 5.5.0, you need to update any PowerShell scripts that are installed to fix this error. See https://github.com/t1m0thyj/WinDynamicDesktop/discussions/582

**Comment by febrimuhnas** [comment]
thankyou
