### ISSUE TITLE
ChangeWindowsAppTheme and ChangeWindowsSystemTheme not useful for my new PC

### ISSUE THREAD

**Issue by Robert13guo** [t1m0thyj/WDD-scripts#5]
Hello,

I recently have a new PC, but it was not worked for me to change the APP and Windows theme automatically.

Any idea what setting I should check?

Robert

**Comment by nick-botticelli** [comment]
Same issue, just installed the latest versions as of today and followed the guide on enabling the scripts, and system/app themes do not change when toggling Night Mode or Refresh Wallpaper option. I'm on latest Windows 10 version and using the GitHub release.

**Comment by snowtyler** [comment]
With Windows 10 21H1 releasing I formatted my system drive and reinstalled Windows with the latest version. Downloaded the app theme/system theme scripts, installed WDD and dropped the scripts in the folder. It doesn't seem to change the theme anymore.

**Comment by yazan1107** [comment]
yes this also happens to me!

**Comment by t1m0thyj** [comment]
Closing as duplicate of https://github.com/t1m0thyj/WDD-scripts/issues/33 and https://github.com/t1m0thyj/WinDynamicDesktop/issues/427
