### ISSUE TITLE
ChangeLockscreenImage not working with certain Windows setting

### ISSUE THREAD

**Issue by zhangyuesai** [t1m0thyj/WDD-scripts#6]
WDD Version: 4.4.0 exe
OS Version: Windows 10 20H2 (19042.867)

The script fails to update with a certain Windows setting: Settings -> Personalization -> Lock screen -> Show lock screen background picture on the sign-in screen. When the setting is OFF, the script works perfectly. When the setting is ON, the lock screen is stuck on the first-ever lock screen image set by the script; the image isn't updated even after selecting a different theme and/or refreshing wallpaper (option in WDD system tray).

I'm not sure if the bug is within Windows or the script.

**Comment by yazan1107** [comment]
yes this also happens to me!
if you find a fix please lemme know!

**Comment by t1m0thyj** [comment]
Closing since WDD 5 supports changing lockscreen image directly in the app without scripts.
