### ISSUE TITLE
How to install PowerShell scripts (standalone)

### ISSUE THREAD

**Issue by yazan1107** [t1m0thyj/WDD-scripts#9]
How to install PowerShell scripts (standalone), there is no guiide for the standalone scripts!

**Comment by t1m0thyj** [comment]
The scripts are called standalone because they can't be installed. Instead they are intended for one-time use to be run directly.

See the note at the top of [the readme](https://github.com/t1m0thyj/WDD-scripts/tree/master/standalone#readme):
> Note: These PowerShell scripts can be run on your PC to tweak Windows settings. They cannot be installed into WinDynamicDesktop.
